<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TRBIR0RI3KICQSJ" name="Case_login" tests="1" failures="1" timestamp="5 May 2017 11:04:11 GMT" time="29.909" errors="0">
  <testcase name="testLogin" time="26.435" classname="top.cases.Case_login">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at top.cases.Case_login.testLogin(Case_login.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testLogin -->
</testsuite> <!-- Case_login -->
